<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'slug'             => 'home',
                'title'            => 'HereNOW Help – Help When and Where You Need It',
                'meta_description' => 'The most holistic & personalized platform for total mental health treatment. Healthcare. Veterans. Students. Employers.',
                'show_hero'        => false,
                'hero_title'       => 'Intelligent Mental Health Platform',
                'hero_subtitle'    => 'The most holistic & personalized platform for total mental health treatment.',
                'show_body'        => false,
                'body'             => null,
                'show_cta'         => false,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => null,
                'is_published'     => true,
            ],
            [
                'slug'             => 'about-story',
                'title'            => 'Our Story – HereNOW Help',
                'meta_description' => 'HereNOW Help was founded with one mission: to make mental health support available to anyone, anywhere, at any time.',
                'show_hero'        => true,
                'hero_title'       => 'Our Story',
                'hero_subtitle'    => 'HereNOW Help was founded with one mission: to make mental health support available to anyone, anywhere, at any time.',
                'show_body'        => true,
                'body'             => '<p>HereNOW Help was built by a passionate team of mental health professionals, technology experts, and advocates who believe that everyone deserves access to quality mental health support — regardless of where they live or what they can afford.</p><p>Our platform brings together the best of technology and human connection to create a holistic, personalized mental health experience for healthcare providers, Veterans, students, employers, and government agencies.</p><p>We believe that with the right tools and community, anyone can manage and improve their mental wellbeing.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'about-vision',
                'title'            => 'Our Vision – HereNOW Help',
                'meta_description' => 'A world where mental health support is available to everyone, everywhere, at any time.',
                'show_hero'        => true,
                'hero_title'       => 'Our Vision',
                'hero_subtitle'    => 'A world where mental health support is available to everyone, everywhere, at any time.',
                'show_body'        => true,
                'body'             => "<p>Our vision is simple: <strong>Help When and Where You Need It.</strong></p><p>We envision a world where the barriers to mental health care — cost, location, stigma, and availability — are eliminated through intelligent technology and compassionate communities.</p><p>HereNOW Help is building the infrastructure for that future: an AI-powered, fully customizable platform that adapts to every user's unique needs, available 24/7/365, meeting people exactly where they are.</p>",
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'veterans',
                'title'            => 'Veterans – HereNOW Help',
                'meta_description' => 'Veteran Mental Wellness Platform. Engage and empower Veterans to understand, track and improve their mental well-being.',
                'show_hero'        => true,
                'hero_title'       => 'Veteran Mental Wellness Platform',
                'hero_subtitle'    => 'Engage and empower Veterans to understand, track and improve their mental well-being.',
                'show_body'        => true,
                'body'             => '<p>HereNOW Help connects Veterans with their care teams, VA Medical Centers, and Veteran Service Organizations through a single holistic platform built specifically for Veteran mental health.</p><p>86% of users report improvement in Happiness and Well-being.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Connect with care teams, VAMCs & VSOs',
                'is_published'     => true,
            ],
            [
                'slug'             => 'students',
                'title'            => 'Students – HereNOW Help',
                'meta_description' => 'Student Wellness Platform. Helping students understand, track and improve their mental well-being.',
                'show_hero'        => true,
                'hero_title'       => 'Student Wellness Platform',
                'hero_subtitle'    => 'Helping students understand, track and improve their mental well-being.',
                'show_body'        => true,
                'body'             => '<p>Learn to manage your own mental wellbeing while also connecting with peers and professionals before, during and after a crisis.</p><p>86% of users improve Happiness and Productivity.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'K-12, Colleges and Universities',
                'is_published'     => true,
            ],
            [
                'slug'             => 'employees',
                'title'            => 'Employees – HereNOW Help',
                'meta_description' => 'Employee Wellness Platform. Engage and empower employees to understand, track and improve their mental wellbeing.',
                'show_hero'        => true,
                'hero_title'       => 'Employee Wellness Platform',
                'hero_subtitle'    => 'Engage and empower employees to understand, track and improve their mental wellbeing.',
                'show_body'        => true,
                'body'             => '<p>86% of users report improvement in Happiness and Productivity. Give your team the tools they need to thrive.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Improve Workplace Mental Health',
                'is_published'     => true,
            ],
            [
                'slug'             => 'rehab',
                'title'            => 'Healthcare – HereNOW Help',
                'meta_description' => 'The most holistic & personalized platform for total mental health treatment. Medical Centers. Rehab Centers. VAMCs.',
                'show_hero'        => true,
                'hero_title'       => 'The Most Holistic & Personalized Platform for Total Mental Health Treatment',
                'hero_subtitle'    => 'Medical Centers. Rehab Centers. VAMCs.',
                'show_body'        => true,
                'body'             => '<p>Tools for intake, assessments, treatment plans and outcome measurements. Stay engaged after discharge, build community, reduce claims and increase referrals.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Stay Engaged After Discharge',
                'is_published'     => true,
            ],
            [
                'slug'             => 'government',
                'title'            => 'Government – HereNOW Help',
                'meta_description' => 'Local & State Government. Helping communities support the mental health and addiction recovery of its residents.',
                'show_hero'        => true,
                'hero_title'       => 'Local & State Government',
                'hero_subtitle'    => 'Helping communities (City, County, State, etc) support the mental health and addiction recovery of its residents.',
                'show_body'        => true,
                'body'             => '<p>Partner with HereNOW Help to provide your residents with 24/7 access to mental health tools, peer support, and licensed professionals.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => "Support Your Community's Mental Health",
                'is_published'     => true,
            ],
            [
                'slug'             => 'peernow',
                'title'            => 'PeerNOW Academy – HereNOW Help',
                'meta_description' => 'Become a Certified Peer Coach. Peer counseling is a scientifically-proven approach to mental health support.',
                'show_hero'        => true,
                'hero_title'       => 'Become a Certified Peer Coach',
                'hero_subtitle'    => 'Peer counseling is a scientifically-proven approach to mental health support. Turn your life experiences into a career helping others.',
                'show_body'        => true,
                'body'             => "<p>Peer counseling is a scientifically-proven approach to mental health support for those in need. Models such as Alcoholics Anonymous (AA) and Narcotics Anonymous (NA) have decades of proven success. These models demonstrate that individuals who have experienced adverse life events can help those who are struggling with similar issues — by lending an empathetic ear, sharing their life experiences, and creating a space where hope and strength can grow.</p>",
                'show_cta'         => false,
                'cta_text'         => 'Get Started',
                'cta_subtext'      => null,
                'is_published'     => true,
            ],
            [
                'slug'             => 'news',
                'title'            => 'Mental Health News – HereNOW Help',
                'meta_description' => 'Stay up to date with the latest in mental health research, trends, and best practices.',
                'show_hero'        => true,
                'hero_title'       => 'Mental Health News',
                'hero_subtitle'    => 'Stay up to date with the latest in mental health research, trends, and best practices.',
                'show_body'        => true,
                'body'             => '<p>The HereNOW Help blog covers the latest developments in mental health treatment, peer support, workplace wellness, Veteran mental health, and student wellbeing.</p><p>Our team of mental health professionals and advocates curates content to help providers, organizations, and individuals stay informed about evidence-based practices and emerging trends.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'peer-counseling',
                'title'            => 'Peer Counseling – HereNOW Help',
                'meta_description' => 'Scientifically-proven peer support for mental health and addiction recovery.',
                'show_hero'        => true,
                'hero_title'       => 'Peer Counseling',
                'hero_subtitle'    => 'Scientifically-proven peer support for mental health and addiction recovery.',
                'show_body'        => true,
                'body'             => '<p>Peer counseling is a scientifically-proven approach where individuals who have lived through similar experiences provide support to those who are struggling. Models like AA and NA have demonstrated decades of success.</p><p>HereNOW Help integrates peer counseling into every aspect of our platform — connecting users with trained peer coaches who can provide empathetic, experienced support around the clock.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'helpful-links',
                'title'            => 'Helpful Links – HereNOW Help',
                'meta_description' => 'Resources and links to support your mental health journey.',
                'show_hero'        => true,
                'hero_title'       => 'Helpful Links',
                'hero_subtitle'    => 'Resources and links to support your mental health journey.',
                'show_body'        => false,
                'body'             => null,
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'support',
                'title'            => 'Support – HereNOW Help',
                'meta_description' => "We're here to help. Any time. Any place. No waiting days or weeks for help.",
                'show_hero'        => true,
                'hero_title'       => 'Customer Support',
                'hero_subtitle'    => "We're here to help. Any time. Any place. No waiting days or weeks for help.",
                'show_body'        => true,
                'body'             => '<p>HereNOW Help provides 24/7/365 support for both providers and clients. Whether you need technical assistance, implementation guidance, or help with your account, our team is ready.</p>',
                'show_cta'         => true,
                'cta_text'         => 'Schedule A Demo',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
            [
                'slug'             => 'team',
                'title'            => 'Our Team – HereNOW Help',
                'meta_description' => 'Meet the people behind HereNOW Help — a dedicated team of mental health professionals, technologists, and advocates.',
                'show_hero'        => true,
                'hero_title'       => 'Our Team',
                'hero_subtitle'    => 'Meet the people behind HereNOW Help — a dedicated team of mental health professionals, technologists, and advocates.',
                'show_body'        => true,
                'body'             => "<p>Our team brings together decades of experience in mental health, technology, education, and public policy. We are united by a shared belief that technology can transform how we deliver and receive mental health support.</p><p>From clinicians and peer specialists to engineers and designers, every member of our team is committed to building a platform that truly makes a difference in people's lives.</p>",
                'show_cta'         => true,
                'cta_text'         => 'Get in Touch',
                'cta_subtext'      => 'Ready to Learn More?',
                'is_published'     => true,
            ],
        ];

        foreach ($pages as $page) {
            Page::updateOrCreate(['slug' => $page['slug']], $page);
        }
    }
}
